basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a Todo web app Server.
  title: Todo App API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
